package model

import (
	"context"
	"errors"
	"time"
)

var ErrFailClosed = errors.New("model execution failed: fail closed")

type ModelRequest struct {
	Prompt          string
	IsSensitive     bool
	HighQuality     bool
	FallbackAllowed bool
}

type ModelResponse struct {
	Text     string
	Provider string
}

type ModelProvider interface {
	Generate(ctx context.Context, req ModelRequest) (ModelResponse, error)
}

type Router struct {
	local    ModelProvider
	external ModelProvider
}

func NewRouter(local, external ModelProvider) *Router {
	return &Router{local: local, external: external}
}

func (r *Router) Route(ctx context.Context, req ModelRequest) (ModelResponse, error) {
	// Sensitive -> local only
	if req.IsSensitive {
		resp, err := r.executeWithTimeout(ctx, r.local, req, 2*time.Second)
		if err != nil {
			return ModelResponse{}, ErrFailClosed
		}
		return resp, nil
	}

	// High quality requirement -> external
	if req.HighQuality {
		return r.executeWithTimeout(ctx, r.external, req, 5*time.Second)
	}

	// Normal -> try local, fallback to external if allowed by policy
	resp, err := r.executeWithTimeout(ctx, r.local, req, 2*time.Second)
	if err != nil {
		if req.FallbackAllowed {
			return r.executeWithTimeout(ctx, r.external, req, 5*time.Second)
		}
		return ModelResponse{}, ErrFailClosed
	}
	return resp, nil
}

func (r *Router) executeWithTimeout(ctx context.Context, provider ModelProvider, req ModelRequest, timeout time.Duration) (ModelResponse, error) {
	ctx, cancel := context.WithTimeout(ctx, timeout)
	defer cancel()

	ch := make(chan struct {
		resp ModelResponse
		err  error
	}, 1)

	go func() {
		resp, err := provider.Generate(ctx, req)
		ch <- struct {
			resp ModelResponse
			err  error
		}{resp, err}
	}()

	select {
	case <-ctx.Done():
		return ModelResponse{}, ctx.Err()
	case res := <-ch:
		return res.resp, res.err
	}
}

// Mock Providers for testing
type MockProvider struct {
	Name       string
	ShouldFail bool
	Delay      time.Duration
}

func (m *MockProvider) Generate(ctx context.Context, req ModelRequest) (ModelResponse, error) {
	if m.Delay > 0 {
		select {
		case <-time.After(m.Delay):
		case <-ctx.Done():
			return ModelResponse{}, ctx.Err()
		}
	}
	
	if m.ShouldFail {
		return ModelResponse{}, errors.New("provider internal error")
	}

	return ModelResponse{
		Text:     "Generated by " + m.Name,
		Provider: m.Name,
	}, nil
}
